/**
 * Scholarship Database for Bhutanese Students
 * International and domestic scholarship opportunities
 */

export interface Scholarship {
  id: string;
  name: string;
  provider: string;
  type: "full" | "partial";
  country: string;
  amount: string;
  field: string;
  eligibility: string;
  deadline: string;
  link: string;
  description: string;
  requirements: string[];
}

export const SCHOLARSHIPS: Scholarship[] = [
  // Bhutan Government Scholarships
  {
    id: "1",
    name: "Royal Scholarship",
    provider: "Royal Government of Bhutan",
    type: "full",
    country: "bhutan",
    amount: "Full tuition + stipend",
    field: "All Fields",
    eligibility: "Class 12 with minimum 70% aggregate",
    deadline: "May annually",
    link: "#",
    description: "Full government scholarship for meritorious students to study abroad.",
    requirements: ["Bhutanese citizen", "Class 12 pass with 70%", "Not employed", "Not over 25 years"],
  },
  {
    id: "2",
    name: "Australia Awards",
    provider: "Australian Government",
    type: "full",
    country: "australia",
    amount: "Full tuition + living expenses",
    field: "All Fields",
    eligibility: "Bachelor's degree with minimum 60%",
    deadline: "May/June annually",
    link: "https://australiaawards.gov.bt",
    description: "Prestigious scholarships for study in Australia at Masters level.",
    requirements: ["Bhutanese citizen", "Bachelor's degree", "2 years work experience", "English proficiency"],
  },
  {
    id: "3",
    name: "New Zealand Excellence Awards",
    provider: "New Zealand Government",
    type: "full",
    country: "new-zealand",
    amount: "Full tuition + living expenses",
    field: "All Fields",
    eligibility: "Class 12 with minimum 75% OR Bachelor's degree",
    deadline: "March annually",
    link: "https://www.studyinnewzealand.govt.nz",
    description: "Scholarships for undergraduate and postgraduate study in New Zealand.",
    requirements: ["Bhutanese citizen", "Strong academic record", "English proficiency (IELTS 6.5+)", "Leadership qualities"],
  },
  // International Scholarships
  {
    id: "4",
    name: "Fulbright Foreign Student Program",
    provider: "US Government",
    type: "full",
    country: "usa",
    amount: "Full tuition + living stipend",
    field: "All Fields",
    eligibility: "Bachelor's degree with high GPA",
    deadline: "October annually",
    link: "https://foreign.fulbrightonline.org",
    description: "Prestigious US government scholarship for graduate study.",
    requirements: ["Bhutanese citizen", "Bachelor's degree", "Strong English (TOEFL 100+)", "GRE/GMAT scores"],
  },
  {
    id: "5",
    name: "Commonwealth Scholarships",
    provider: "UK Government",
    type: "full",
    country: "uk",
    amount: "Full tuition + living stipend",
    field: "Development Related",
    eligibility: "Bachelor's degree with minimum 60%",
    deadline: "October-December annually",
    link: "https://cscuk.fcdo.service.gov.uk",
    description: "UK government scholarships for Masters study in development-related fields.",
    requirements: ["Commonwealth citizen", "Bachelor's degree", "Commitment to return home", "2 years work experience"],
  },
  {
    id: "6",
    name: "DAAD Scholarships",
    provider: "German Government",
    type: "full",
    country: "germany",
    amount: "Full tuition + monthly stipend",
    field: "All Fields",
    eligibility: "Bachelor's degree",
    deadline: "Varies (July-October)",
    link: "https://www.daad.de",
    description: "German government scholarships for study in Germany (many programs in English).",
    requirements: ["Bachelor's degree", "English proficiency", "Not studied in Germany before", "Under 35 preferred"],
  },
  {
    id: "7",
    name: "Singapore Scholarship",
    provider: "Singapore Government",
    type: "full",
    country: "singapore",
    amount: "Full tuition + accommodation + living",
    field: "Engineering, Science, Technology",
    eligibility: "Class 12 with minimum 85% in Science/Math",
    deadline: "March-April annually",
    link: "https://www.moe.gov.sg",
    description: "Full undergraduate scholarship for top students to study at NUS, NTU, or SUTD.",
    requirements: ["Bhutanese citizen", "Class 12 science stream", "Minimum 85% aggregate", "Strong English", "Extra-curriculars"],
  },
  // Regional Scholarships
  {
    id: "8",
    name: "ASEAN Undergraduate Scholarship",
    provider: "Singapore Government",
    type: "full",
    country: "singapore",
    amount: "Full tuition + accommodation + living",
    field: "All Fields",
    eligibility: "Class 12 with minimum 85%",
    deadline: "April annually",
    link: "https://www.moe.gov.sg",
    description: "Full scholarship for undergraduate study at NUS, NTU, SMU, or SUTD.",
    requirements: ["From ASEAN member (including Bhutan)", "Strong academic record", "Leadership potential", "English proficiency"],
  },
  {
    id: "9",
    name: "Chevening Scholarships",
    provider: "UK Government",
    type: "full",
    country: "uk",
    amount: "Full tuition + monthly stipend",
    field: "All Fields",
    eligibility: "Bachelor's degree + 2 years work experience",
    deadline: "November annually",
    link: "https://www.chevening.org",
    description: "UK government's global scholarship programme for future leaders.",
    requirements: ["Bhutanese citizen", "Bachelor's degree", "2 years work experience", "Leadership potential", "Return to home country"],
  },
  {
    id: "10",
    name: "Erasmus Mundus",
    provider: "European Union",
    type: "full",
    country: "europe",
    amount: "Full tuition + travel + living",
    field: "Varies by program",
    eligibility: "Bachelor's degree",
    deadline: "Varies (Oct-Feb)",
    link: "https://www.eulpplus.eu",
    description: "EU-funded scholarships to study in multiple European countries.",
    requirements: ["Bachelor's degree", "English proficiency", "Academic excellence", "Not lived in EU before"],
  },
  // University-Specific Scholarships
  {
    id: "11",
    name: "NUS Global Merit Scholarship",
    provider: "National University of Singapore",
    type: "full",
    country: "singapore",
    amount: "Full tuition + living + accommodation",
    field: "All Fields",
    eligibility: "Class 12 with minimum 90%",
    deadline: "March annually",
    link: "https://www.nus.edu.sg",
    description: "Prestigious scholarship for top students at National University of Singapore.",
    requirements: ["Outstanding academic results", "Strong co-curricular record", "Leadership qualities", "Good moral character"],
  },
  {
    id: "12",
    name: "NTU Science & Engineering Scholarship",
    provider: "Nanyang Technological University",
    type: "full",
    country: "singapore",
    amount: "Full tuition + living allowance",
    field: "Science, Engineering, Technology",
    eligibility: "Class 12 with minimum 85% in Science",
    deadline: "March annually",
    link: "https://www.ntu.edu.sg",
    description: "Full scholarship for Science & Engineering students at NTU Singapore.",
    requirements: ["Science stream in Class 12", "Strong math and science grades", "English proficiency", "Innovation/Research interest"],
  },
  {
    id: "13",
    name: "UNSW International Scholarship",
    provider: "University of New South Wales",
    type: "partial",
    country: "australia",
    amount: "$10,000 AUD/year",
    field: "All Fields",
    eligibility: "Class 12 with minimum 75%",
    deadline: "July/September annually",
    link: "https://www.unsw.edu.au",
    description: "Partial scholarship for international students at UNSW Sydney.",
    requirements: ["International student", "Strong academic record", "Not holding other scholarships", "Full-time enrollment"],
  },
  {
    id: "14",
    name: "University of Melbourne Chancellor's Scholarship",
    provider: "University of Melbourne",
    type: "full",
    country: "australia",
    amount: "Full tuition + living + one-way flight",
    field: "All Fields",
    eligibility: "Class 12 with minimum 90%",
    deadline: "October annually",
    link: "https://www.unimelb.edu.au",
    description: "Prestigious full scholarship for top students at University of Melbourne.",
    requirements: ["Exceptional academic achievement", "Leadership potential", "Community involvement", "Not commenced previous tertiary study"],
  },
  // Special Scholarships
  {
    id: "15",
    name: "Rotary Foundation Global Grant",
    provider: "Rotary International",
    type: "full",
    country: "various",
    amount: "$30,000 USD",
    field: "Peace, Disease Prevention, Water, Maternal Health",
    eligibility: "Bachelor's degree + work experience",
    deadline: "Varies",
    link: "https://www.rotary.org",
    description: "Scholarships for graduate-level study in peace and conflict prevention.",
    requirements: ["Proposed field of study aligns with Rotary's areas", "Bachelor's degree", "Proficiency in language of study", "Citizen of country with Rotary club"],
  },
  {
    id: "16",
    name: "MasterCard Foundation Scholars Program",
    provider: "MasterCard Foundation",
    type: "full",
    country: "various (US, Canada, Europe, Africa)",
    amount: "Full tuition + living + stipend + travel",
    field: "All Fields",
    eligibility: "Economically disadvantaged",
    deadline: "Varies by university",
    link: "https://www.mastercardfdn.org",
    description: "Full scholarship for economically disadvantaged students with academic potential.",
    requirements: ["Economic disadvantage", "Academic talent", "Leadership potential", "Commitment to give back to community", "From Sub-Saharan Africa or refugee/displaced"],
  },
];
