-- Migration: attendance
-- Generated by Unified Architecture
-- Feature: src/features/attendance.feature.tsx

CREATE TABLE IF NOT EXISTS attendance (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid(),
  studentId TEXT NOT NULL,
  classId TEXT NOT NULL,
  schoolId TEXT,
  date TEXT NOT NULL,
  checkInTime TEXT,
  status TEXT NOT NULL,
  recordedBy TEXT,
  notes TEXT,
  reason TEXT,
  entryMethod TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT attendance_studentId_fk FOREIGN KEY (studentId) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT attendance_classId_fk FOREIGN KEY (classId) REFERENCES classes (id) ON DELETE NO ACTION,
  CONSTRAINT attendance_schoolId_fk FOREIGN KEY (schoolId) REFERENCES schools (id) ON DELETE NO ACTION,
  CONSTRAINT attendance_recordedBy_fk FOREIGN KEY (recordedBy) REFERENCES users (id) ON DELETE SET NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance (date);
CREATE INDEX IF NOT EXISTS idx_attendance_status ON attendance (status);
CREATE INDEX IF NOT EXISTS idx_attendance_studentId ON attendance (studentId);
CREATE INDEX IF NOT EXISTS idx_attendance_classId ON attendance (classId);
CREATE INDEX IF NOT EXISTS idx_attendance_schoolId ON attendance (schoolId);

COMMENT ON TABLE attendance IS 'Student attendance records with check-in/check-out tracking';
