/**
 * LearningPath Feature Definition
 *
 * Auto-generated by migration script
 * Generated: 2026-03-04T06:20:27.655Z
 */

import { defineFeature } from "@/lib/features/define-feature";

export const LearningPathFeature = defineFeature({
  name: "learning_paths",
  tableName: "learning_paths",

  schema: {
    id: {
      type: "text",
      required: true,
      primary: true,
      label: "ID",
    },
    name: {
      type: "text",
      required: true,
      label: "Name",
      sortable: true,
    },
    createdAt: {
      type: "timestamp",
      label: "Created At",
      sortable: true,
    },
    updatedAt: {
      type: "timestamp",
      label: "Updated At",
      sortable: true,
    },
  },

  permissions: {
    read: ["school-admin", "teacher", "ministry"],
    create: ["school-admin"],
    update: ["school-admin"],
    delete: ["school-admin"],
  },

  ui: {
    title: "LearningPath",
    titlePlural: "LearningPaths",
    basePath: "/admin/learning_paths",
    icon: "FileText",
    columns: [
      { key: "name", label: "Name", sortable: true },
      { key: "createdAt", label: "Created", sortable: true },
    ],
  },
});
