/**
 * REPORTS FEATURE DEFINITION
 */

import { defineFeature } from "@/lib/features/define-feature";

export const ReportFeature = defineFeature({
  name: "reports",
  tableName: "reports",

  schema: {
    id: { type: "text", required: true, primary: true },
    title: { type: "text", required: true, label: "Report Title", sortable: true, searchable: true },
    reportType: { type: "enum", options: ["student", "class", "subject", "school", "attendance", "fees", "exam"], label: "Type", filterable: true },
    schoolId: { type: "reference", reference: { table: "schools", onDelete: "cascade" } },
    classId: { type: "reference", reference: { table: "classes", onDelete: "set null" }, label: "Class" },
    generatedBy: { type: "reference", reference: { table: "users", onDelete: "set null" } },
    generatedFor: { type: "reference", reference: { table: "users", onDelete: "set null" }, label: "Generated For" },
    reportData: { type: "json", label: "Report Data" },
    dateFrom: { type: "date", label: "From Date" },
    dateTo: { type: "date", label: "To Date" },
    format: { type: "enum", options: ["pdf", "excel", "csv"], label: "Format" },
    fileUrl: { type: "text", label: "File URL" },
    status: { type: "enum", options: ["generating", "ready", "failed"], label: "Status", filterable: true },
    createdAt: { type: "timestamp", sortable: true },
    updatedAt: { type: "timestamp", sortable: true },
  },

  permissions: {
    read: ["school-admin", "teacher", "admin"],
    create: ["school-admin", "teacher", "admin"],
    update: ["school-admin", "admin"],
    delete: ["school-admin", "admin"],
  },

  ui: {
    title: "Report",
    titlePlural: "Reports",
    basePath: "/school-admin/reports",
    columns: [
      { key: "title", label: "Title", sortable: true },
      { key: "reportType", label: "Type", filterable: true },
      { key: "dateFrom", label: "Period", type: "date" },
      { key: "generatedByName", label: "Generated By" },
      { key: "status", label: "Status", filterable: true },
      { key: "createdAt", label: "Created", type: "date" },
    ],
  },

  customHandlers: {
    list: async (params: any, auth: any) => {
      const { db } = await import("@/lib/db");
      const { reports, classes, users } = await import("@/lib/db/schema");
      const { eq, and, desc, sql } = await import("drizzle-orm");

      const { page = "1", limit = "20", reportType, classId, status } = params;
      const offset = (parseInt(page) - 1) * parseInt(limit);

      const conditions = [];
      if (auth.user?.schoolId) conditions.push(eq(reports.schoolId, auth.user.schoolId));
      if (reportType) conditions.push(eq(reports.reportType, reportType));
      if (classId) conditions.push(eq(reports.classId, classId));
      if (status) conditions.push(eq(reports.status, status));

      const whereClause = conditions.length > 0 ? and(...conditions) : undefined;

      const data = await db
        .select({
          id: reports.id,
          title: reports.title,
          reportType: reports.reportType,
          dateFrom: reports.dateFrom,
          dateTo: reports.dateTo,
          format: reports.format,
          status: reports.status,
          fileUrl: reports.fileUrl,
          createdAt: reports.createdAt,
          className: classes.name,
          generatedByName: sql<string>`concat(${users.firstName}, ' ', ${users.lastName})`,
        })
        .from(reports)
        .leftJoin(classes, eq(reports.classId, classes.id))
        .leftJoin(users, eq(reports.generatedBy, users.id))
        .where(whereClause)
        .orderBy(desc(reports.createdAt))
        .limit(parseInt(limit))
        .offset(offset);

      const [{ count }] = await db
        .select({ count: sql<number>`count(*)::int` })
        .from(reports)
        .where(whereClause);

      return {
        success: true,
        data: { data, pagination: { total: count, page: parseInt(page), limit: parseInt(limit), totalPages: Math.ceil(count / parseInt(limit)) } },
      };
    },
  },

  bulkOperations: {
    generateAttendanceReport: async (classId: string, dateFrom: string, dateTo: string, auth: any) => {
      const { db } = await import("@/lib/db");
      const { reports, attendance } = await import("@/lib/db/schema");
      const { nanoid } = await import("nanoid");
      const { eq, and, gte, lte, count, sql } = await import("drizzle-orm");

      // Get attendance data
      const data = await db
        .select({
          status: attendance.status,
          count: count(),
        })
        .from(attendance)
        .where(
          and(
            eq(attendance.classId, classId),
            gte(attendance.date, dateFrom),
            lte(attendance.date, dateTo)
          )
        )
        .groupBy(attendance.status);

      // Create report record
      const [report] = await db.insert(reports).values({
        id: nanoid(),
        title: `Attendance Report - ${dateFrom} to ${dateTo}`,
        reportType: "attendance",
        schoolId: auth.user?.schoolId,
        classId,
        generatedBy: auth.user?.id,
        reportData: JSON.stringify(data),
        dateFrom,
        dateTo,
        status: "ready",
        createdAt: new Date(),
        updatedAt: new Date(),
      }).returning();

      return { success: true, data: report };
    },
  },
});
