import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { db } from "@/lib/db";
import { users } from "@/lib/db/schema";
import { eq, and, desc } from "drizzle-orm";
import { nanoid } from "nanoid";

// ============================================================================
// POST /api/reports/generate - Generate government report
// ============================================================================

export async function POST(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const currentUser = await db.query.users.findFirst({
      where: eq(users.clerkUserId, userId),
    });

    if (!currentUser) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const body = await request.json();
    const {
      templateId,
      reportPeriod,
      reportingPeriodStart,
      reportingPeriodEnd,
      dueDate,
      autoGenerateData,
    } = body;

    if (!templateId || !reportPeriod) {
      return NextResponse.json(
        { error: "Missing required fields: templateId, reportPeriod" },
        { status: 400 }
      );
    }

    const {
      reportTemplates: reportTemplatesTable,
      generatedReports: generatedReportsTable,
    } = await import("@/lib/db/reports-schema");

    // Get template
    const template = await db.query.reportTemplates.findFirst({
      where: eq(reportTemplatesTable.id, templateId),
    });

    if (!template) {
      return NextResponse.json({ error: "Template not found" }, { status: 404 });
    }

    // Generate report data based on template
    let reportData = {};
    let summary = "";

    if (autoGenerateData) {
      // Auto-generate data based on report type
      const generated = await generateReportData(
        template.code,
        currentUser.schoolId || "",
        reportPeriod,
        reportingPeriodStart,
        reportingPeriodEnd
      );
      reportData = generated.data;
      summary = generated.summary;
    }

    // Create generated report
    const [report] = await db.insert(generatedReportsTable).values({
      id: nanoid(),
      schoolId: currentUser.schoolId || "",
      templateId,
      reportName: `${template.name} - ${reportPeriod}`,
      reportCode: `${template.code}-${reportPeriod}`,
      reportPeriod,
      reportingPeriodStart,
      reportingPeriodEnd,
      generatedDate: new Date().toISOString(),
      dueDate,
      status: "draft",
      reportData,
      summary,
      preparedBy: currentUser.id,
      preparedDate: new Date().toISOString(),
      agency: template.agency,
      reportType: template.reportType,
      frequency: template.frequency,
      createdAt: new Date(),
      updatedAt: new Date(),
    }).returning();

    // Create specific report type data
    await createSpecificReportData(report.id, template.code, currentUser.schoolId || "", reportData);

    return NextResponse.json({ report }, { status: 201 });
  } catch (error) {
    console.error("Report generation error:", error);
    return NextResponse.json({ error: "Failed to generate report" }, { status: 500 });
  }
}

// ============================================================================
// Helper function to generate report data based on type
// ============================================================================

async function generateReportData(
  templateCode: string,
  schoolId: string,
  reportPeriod: string,
  periodStart?: string,
  periodEnd?: string
): Promise<{ data: Record<string, any>; summary: string }> {
  const data: Record<string, any> = {
    schoolId,
    reportPeriod,
    generatedAt: new Date().toISOString(),
  };

  let summary = "";

  switch (templateCode) {
    case "STU_ATTEND": {
      // Student attendance report
      const { students: studentsTable, attendance: attendanceTable } = await import("@/lib/db/schema");

      const students = await db.query.students.findMany({
        where: eq(studentsTable.schoolId, schoolId),
      });

      data.totalStudents = students.length;
      data.reportPeriod = reportPeriod;
      summary = `${students.length} students enrolled for ${reportPeriod}`;

      // Calculate attendance rates
      // In production, would query attendance table
      data.overallAttendanceRate = 85; // Placeholder
      break;
    }

    case "STU_PERF": {
      // Student performance report
      data.totalStudents = 0;
      data.overallPassPercentage = 0;
      summary = "Student performance report";
      break;
    }

    case "INFRA": {
      // Infrastructure report
      data.totalClassrooms = 20;
      data.hasLibrary = true;
      data.hasComputerLab = true;
      data.computerCount = 30;
      summary = "Infrastructure report";
      break;
    }

    case "STAFF": {
      // Staff report
      const { teachers: teachersTable } = await import("@/lib/db/schema");

      const teachers = await db.query.teachers.findMany({
        where: eq(teachersTable.schoolId, schoolId),
      });

      data.totalTeachers = teachers.length;
      data.totalNonTeachingStaff = 10;
      data.totalStaff = teachers.length + 10;
      summary = `${teachers.length} teachers, ${data.totalStaff} total staff`;
      break;
    }

    case "FINANCE": {
      // Financial report
      data.governmentGrant = 500000;
      data.schoolFees = 100000;
      data.totalIncome = 600000;
      data.salaries = 400000;
      data.totalExpenditure = 550000;
      summary = "Financial report";
      break;
    }

    case "DEMOG": {
      // Demographic report
      data.totalEnrollment = 500;
      data.newEnrollment = 50;
      data.genderBreakdown = { male: 260, female: 240 };
      summary = "Demographic report";
      break;
    }

    default:
      summary = `${templateCode} report for ${reportPeriod}`;
  }

  return { data, summary };
}

// ============================================================================
// Helper function to create specific report type records
// ============================================================================

async function createSpecificReportData(
  reportId: string,
  templateCode: string,
  schoolId: string,
  reportData: Record<string, any>
): Promise<void> {
  switch (templateCode) {
    case "STU_ATTEND": {
      const { studentAttendanceReports: studentAttendanceReportsTable } = await import("@/lib/db/reports-schema");
      await db.insert(studentAttendanceReportsTable).values({
        id: nanoid(),
        schoolId,
        reportId,
        academicYear: reportData.reportPeriod,
        period: "annual",
        periodStart: reportData.reportingPeriodStart || new Date().toISOString(),
        periodEnd: reportData.reportingPeriodEnd || new Date().toISOString(),
        totalStudents: reportData.totalStudents || 0,
        totalPresentDays: 0,
        totalAbsentDays: 0,
        overallAttendanceRate: reportData.overallAttendanceRate || 0,
        classWiseData: [],
        chronicAbsentees: [],
        absenceReasons: [],
        createdAt: new Date(),
      });
      break;
    }

    case "STU_PERF": {
      const { studentPerformanceReports: studentPerformanceReportsTable } = await import("@/lib/db/reports-schema");
      await db.insert(studentPerformanceReportsTable).values({
        id: nanoid(),
        schoolId,
        reportId,
        academicYear: reportData.reportPeriod,
        examType: "final",
        totalStudents: 0,
        totalAppeared: 0,
        overallPassPercentage: 0,
        overallDistinctionPercentage: 0,
        firstDivisionCount: 0,
        secondDivisionCount: 0,
        thirdDivisionCount: 0,
        failedCount: 0,
        subjectPerformance: [],
        classPerformance: [],
        topPerformers: [],
        yearComparison: {},
        createdAt: new Date(),
      });
      break;
    }

    case "INFRA": {
      const { infrastructureReports: infrastructureReportsTable } = await import("@/lib/db/reports-schema");
      await db.insert(infrastructureReportsTable).values({
        id: nanoid(),
        schoolId,
        reportId,
        reportingDate: new Date().toISOString(),
        academicYear: reportData.reportPeriod,
        totalClassrooms: reportData.totalClassrooms || 0,
        totalOtherRooms: 0,
        roomBreakdown: [],
        hasLibrary: reportData.hasLibrary || false,
        hasScienceLab: false,
        hasComputerLab: reportData.hasComputerLab || false,
        computerCount: reportData.computerCount || 0,
        hasPlayground: false,
        buildingCondition: "good",
        maintenanceRequired: [],
        createdAt: new Date(),
      });
      break;
    }

    case "STAFF": {
      const { staffReports: staffReportsTable } = await import("@/lib/db/reports-schema");
      await db.insert(staffReportsTable).values({
        id: nanoid(),
        schoolId,
        reportId,
        academicYear: reportData.reportPeriod,
        reportingDate: new Date().toISOString(),
        totalStaff: reportData.totalStaff || 0,
        totalTeachers: reportData.totalTeachers || 0,
        totalNonTeachingStaff: reportData.totalNonTeachingStaff || 0,
        teachingStaffBreakdown: [],
        qualificationBreakdown: [],
        subjectTeachers: [],
        experienceBreakdown: [],
        newRecruits: 0,
        resigned: 0,
        retired: 0,
        transferred: 0,
        totalVacancies: 0,
        vacancyDetails: [],
        trainingConducted: [],
        createdAt: new Date(),
      });
      break;
    }

    case "FINANCE": {
      const { financialReports: financialReportsTable } = await import("@/lib/db/reports-schema");
      await db.insert(financialReportsTable).values({
        id: nanoid(),
        schoolId,
        reportId,
        financialYear: reportData.reportPeriod,
        reportingDate: new Date().toISOString(),
        governmentGrant: reportData.governmentGrant || 0,
        schoolFees: reportData.schoolFees || 0,
        otherIncome: reportData.otherIncome || 0,
        totalIncome: reportData.totalIncome || 0,
        salaries: reportData.salaries || 0,
        utilities: 0,
        maintenance: 0,
        supplies: 0,
        capitalExpenditure: 0,
        otherExpenditure: 0,
        totalExpenditure: reportData.totalExpenditure || 0,
        openingBalance: 0,
        closingBalance: 0,
        surplusDeficit: 0,
        grantDetails: [],
        audited: false,
        createdAt: new Date(),
      });
      break;
    }

    case "DEMOG": {
      const { demographicReports: demographicReportsTable } = await import("@/lib/db/reports-schema");
      await db.insert(demographicReportsTable).values({
        id: nanoid(),
        schoolId,
        reportId,
        academicYear: reportData.reportPeriod,
        asOfDate: new Date().toISOString(),
        totalEnrollment: reportData.totalEnrollment || 0,
        newEnrollment: reportData.newEnrollment || 0,
        genderBreakdown: reportData.genderBreakdown || {},
        dzongkhagBreakdown: [],
        ageDistribution: [],
        specialNeedsStudents: 0,
        specialNeedsBreakdown: [],
        eccdEnrollment: 0,
        dropoutData: [],
        createdAt: new Date(),
      });
      break;
    }
  }
}

// ============================================================================
// GET /api/reports/generate - Get available report templates
// ============================================================================

export async function GET(request: NextRequest) {
  try {
    const { userId } = await auth();
    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const currentUser = await db.query.users.findFirst({
      where: eq(users.clerkUserId, userId),
    });

    if (!currentUser) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const { reportTemplates: reportTemplatesTable } = await import("@/lib/db/reports-schema");

    const templates = await db.query.reportTemplates.findMany({
      where: eq(reportTemplatesTable.isActive, true),
      orderBy: [reportTemplatesTable.name],
    });

    // Group by agency
    const grouped = templates.reduce((acc, template) => {
      if (!acc[template.agency]) {
        acc[template.agency] = [];
      }
      acc[template.agency].push(template);
      return acc;
    }, {} as Record<string, typeof templates>);

    return NextResponse.json({
      templates: grouped,
      allTemplates: templates,
    });
  } catch (error) {
    console.error("Report templates fetch error:", error);
    return NextResponse.json({ error: "Failed to fetch templates" }, { status: 500 });
  }
}
