/**
 * SEED DIVERSE CAREERS FOR BHUTAN'S 60,000+ STUDENTS
 *
 * This includes careers for ALL types of students, not just top performers:
 * - Entry-level government jobs
 * - Skilled trades and vocational careers
 * - Arts and traditional Bhutanese crafts
 * - Service industry jobs
 * - Agriculture and farming
 * - Small business and self-employment
 * - Transportation
 * - Retail and sales
 *
 * Run: npx tsx scripts/seed-diverse-careers.ts
 */

import "dotenv/config";
import { db } from "@/lib/db";
import { careers } from "@/lib/db/schema";
import { nanoid } from "nanoid";
import { eq } from "drizzle-orm";

// ============================================================================
// ENTRY-LEVEL GOVERNMENT & CIVIL SERVICE
// ============================================================================

const GOVERNMENT_CAREERS = [
  {
    id: "career-liaison-officer",
    title: "Liaison Officer",
    name: "Liaison Officer",
    slug: "liaison-officer",
    description: "Serve as a connection between government departments and the public. Handle correspondence, coordinate meetings, and facilitate communication.",
    category: "Government",
    industry: "Civil Service",
    riasecCode: "SEC",
    hollandCodes: ["S", "E", "C"],
    educationLevel: "class12",
    typicalSalary: "Nu. 12,000 - 25,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Communication", "Documentation", "Coordination", "Dzongkha", "English", "Basic Computer"],
    subjects: ["English", "Dzongkha", "Computer Skills"],
    workEnvironment: "Government Office",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "users",
    color: "#dc2626",
  },
  {
    id: "career-clerk",
    title: "Office Clerk",
    name: "Office Clerk",
    slug: "office-clerk",
    description: "Handle administrative tasks in government or private offices. Maintain files, prepare documents, data entry, and assist with daily office operations.",
    category: "Government",
    industry: "Administration",
    riasecCode: "C",
    hollandCodes: ["C"],
    educationLevel: "class12",
    typicalSalary: "Nu. 10,000 - 20,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Typing", "Filing", "Data Entry", "Basic Computer", "Organization"],
    subjects: ["Computer Skills", "English", "Mathematics"],
    workEnvironment: "Office",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "file-text",
    color: "#6b7280",
  },
  {
    id: "career-data-entry-operator",
    title: "Data Entry Operator",
    name: "Data Entry Operator",
    slug: "data-entry-operator",
    description: "Input and maintain data in computer systems. Work with various government departments and private organizations for digital record keeping.",
    category: "Government",
    industry: "Administration",
    riasecCode: "C",
    hollandCodes: ["C"],
    educationLevel: "class12",
    typicalSalary: "Nu. 10,000 - 18,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Typing", "MS Excel", "MS Word", "Attention to Detail", "Accuracy"],
    subjects: ["Computer Applications", "English", "Mathematics"],
    workEnvironment: "Office",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [],
    icon: "keyboard",
    color: "#3b82f6",
  },
  {
    id: "career-gsadiv",
    title: "Gup / Tshogpa (Local Government)",
    name: "Local Government Representative",
    slug: "gup-tshogpa",
    description: "Represent local community at the gewog or chiwog level. Lead development initiatives, resolve disputes, and coordinate with government agencies.",
    category: "Government",
    industry: "Local Government",
    riasecCode: "S",
    hollandCodes: ["S"],
    educationLevel: "class10",
    typicalSalary: "Nu. 15,000 - 30,000/month + allowances",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Leadership", "Public Speaking", "Conflict Resolution", "Community Relations", "Dzongkha"],
    subjects: ["Dzongkha", "English", "Social Studies"],
    workEnvironment: "Gewog Office, Community",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "landmark",
    color: "#f59e0b",
  },
  {
    id: "career-forest-ranger",
    title: "Forest Ranger",
    name: "Forest Ranger",
    slug: "forest-ranger",
    description: "Protect Bhutan's forests and wildlife. Monitor forest areas, prevent poaching and illegal logging, and promote conservation.",
    category: "Government",
    industry: "Environment",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class12",
    typicalSalary: "Nu. 15,000 - 28,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Outdoor Skills", "Wildlife Knowledge", "Physical Fitness", "Observation", "Navigation"],
    subjects: ["Biology", "Geography", "Environmental Studies"],
    workEnvironment: "Forest, Field",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "trees",
    color: "#22c55e",
  },
  {
    id: "career-taxi-driver",
    title: "Taxi Driver",
    name: "Taxi Driver",
    slug: "taxi-driver",
    description: "Provide transportation services to passengers. Operate taxi in urban and rural areas, serve tourists and locals.",
    category: "Transportation",
    industry: "Transportation",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 25,000/month (varies)",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Driving", "Navigation", "Customer Service", "Basic Vehicle Maintenance", "Road Safety"],
    subjects: ["Driving License Required"],
    workEnvironment: "Vehicle, Road",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "car",
    color: "#64748b",
  },
  {
    id: "career-postal-worker",
    title: "Postal Worker",
    name: "Postal Worker",
    slug: "postal-worker",
    description: "Sort and deliver mail to homes and businesses. Work at post offices handling mail, packages, and postal services.",
    category: "Government",
    industry: "Postal Service",
    riasecCode: "C",
    hollandCodes: ["C"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 18,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "low",
    skills: ["Sorting", "Organization", "Customer Service", "Basic Computer"],
    subjects: ["English", "Mathematics"],
    workEnvironment: "Post Office",
    bhutanSpecific: true,
    bhutanDemand: "low",
    rubPrograms: [],
    icon: "mail",
    color: "#8b5cf6",
  },
];

// ============================================================================
// SKILLED TRADES & VOCATIONAL
// ============================================================================

const TRADE_CAREERS = [
  {
    id: "career-painter",
    title: "Painter (House/Commercial)",
    name: "Painter",
    slug: "painter",
    description: "Paint buildings, houses, and commercial spaces. Prepare surfaces, apply paint, and create decorative finishes.",
    category: "Skilled Trades",
    industry: "Construction",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 12,000 - 25,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Painting Techniques", "Surface Preparation", "Color Mixing", "Safety Practices", "Time Management"],
    subjects: ["Art", "Mathematics"],
    workEnvironment: "Construction Site, Indoor/Outdoor",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "tti-thimphu", programId: "cert-construction", programName: "Certificate in Construction at TTI" },
      { collegeId: "wti", programId: "diploma-painting", programName: "Diploma in Painting at WTI" },
    ],
    icon: "brush",
    color: "#ef4444",
  },
  {
    id: "career-carpenter",
    title: "Carpenter",
    name: "Carpenter",
    slug: "carpenter",
    description: "Build and repair wooden structures, furniture, and fixtures. Work on construction sites and in workshops.",
    category: "Skilled Trades",
    industry: "Construction",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 15,000 - 30,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Woodworking", "Measuring", "Cutting", "Assembly", "Blueprint Reading"],
    subjects: ["Mathematics", "Technical Drawing"],
    workEnvironment: "Workshop, Construction Site",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "tti-thimphu", programId: "cert-carpentry", programName: "Certificate in Carpentry at TTI" },
    ],
    icon: "hammer",
    color: "#a16207",
  },
  {
    id: "career-electrician-helper",
    title: "Electrician Helper",
    name: "Electrician Helper",
    slug: "electrician-helper",
    description: "Assist electricians in installing and maintaining electrical systems. Learn the trade and advance to licensed electrician.",
    category: "Skilled Trades",
    industry: "Construction",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 18,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Basic Electrical Knowledge", "Safety Practices", "Physical Stamina", "Tool Handling"],
    subjects: ["Physics", "Mathematics"],
    workEnvironment: "Construction Site, Building",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "zap",
    color: "#eab308",
  },
  {
    id: "career-plumber",
    title: "Plumber",
    name: "Plumber",
    slug: "plumber",
    description: "Install and repair water supply systems, drainage systems, and plumbing fixtures. Essential for construction and maintenance.",
    category: "Skilled Trades",
    industry: "Construction",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 15,000 - 28,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Pipe Fitting", "Leak Detection", "Installation", "Problem Solving", "Safety"],
    subjects: ["Mathematics", "Physics"],
    workEnvironment: "Construction Site, Indoor",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "tti-thimphu", programId: "cert-plumbing", programName: "Certificate in Plumbing at TTI" },
    ],
    icon: "wrench",
    color: "#3b82f6",
  },
  {
    id: "career-mason",
    title: "Mason",
    name: "Mason",
    slug: "mason",
    description: "Build and repair structures using bricks, concrete blocks, and stone. Work on walls, foundations, and buildings.",
    category: "Skilled Trades",
    industry: "Construction",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 12,000 - 25,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Brick Laying", "Concrete Mixing", "Reading Blueprints", "Physical Stamina"],
    subjects: ["Mathematics"],
    workEnvironment: "Construction Site",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [],
    icon: "blocks",
    color: "#78716c",
  },
  {
    id: "career-welder",
    title: "Welder",
    name: "Welder",
    slug: "welder",
    description: "Join metal parts using welding techniques. Work in construction, manufacturing, and repair shops.",
    category: "Skilled Trades",
    industry: "Manufacturing",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 15,000 - 30,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Welding Techniques", "Metal Cutting", "Safety Procedures", "Blueprint Reading"],
    subjects: ["Physics", "Mathematics"],
    workEnvironment: "Workshop, Factory",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "tti-thimphu", programId: "cert-welding", programName: "Certificate in Welding at TTI" },
    ],
    icon: "flame",
    color: "#f97316",
  },
  {
    id: "career-auto-mechanic",
    title: "Auto Mechanic",
    name: "Auto Mechanic",
    slug: "auto-mechanic",
    description: "Repair and maintain vehicles including cars, trucks, and SUVs. Diagnose problems and perform repairs.",
    category: "Skilled Trades",
    industry: "Automotive",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 12,000 - 28,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Engine Repair", "Diagnostics", "Electrical Systems", "Problem Solving"],
    subjects: ["Physics", "Mathematics"],
    workEnvironment: "Garage, Workshop",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "tti-thimphu", programId: "diploma-auto", programName: "Diploma in Automotive at TTI" },
      { collegeId: "wti", programId: "cert-auto", programName: "Certificate in Automotive at WTI" },
    ],
    icon: "wrench",
    color: "#dc2626",
  },
  {
    id: "career-tailor",
    title: "Tailor",
    name: "Tailor",
    slug: "tailor",
    description: "Stitch and alter clothes including traditional Bhutanese attire (gho, kira) and modern garments. Can run own business.",
    category: "Skilled Trades",
    industry: "Textile",
    riasecCode: "A",
    hollandCodes: ["A"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 10,000 - 25,000/month (self-employed: varies)",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Sewing", "Cutting", "Measurement", "Design", "Embroidery"],
    subjects: ["Art", "Mathematics"],
    workEnvironment: "Tailoring Shop, Home",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "scissors",
    color: "#ec4899",
  },
];

// ============================================================================
// ARTS & TRADITIONAL BHUTANESE CRAFTS
// ============================================================================

const ARTS_CAREERS = [
  {
    id: "career-thangka-painter",
    title: "Thangka Painter",
    name: "Thangka Painter",
    slug: "thangka-painter",
    description: "Create traditional Buddhist thangka paintings. Highly skilled art form with cultural and religious significance.",
    category: "Arts & Culture",
    industry: "Arts",
    riasecCode: "A",
    hollandCodes: ["A"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 15,000 - 40,000/month (varies by skill)",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Painting", "Patience", "Detail Orientation", "Buddhist Iconography", "Color Theory"],
    subjects: ["Art", "Buddhist Studies"],
    workEnvironment: "Studio, Monastery",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [
      { collegeId: "vab", programId: "cert-thangka", programName: "Certificate in Thangka Painting at VAB" },
    ],
    icon: "palette",
    color: "#fbbf24",
  },
  {
    id: "career-traditional-painter",
    title: "Traditional Painter (House/Monastery)",
    name: "Traditional Painter",
    slug: "traditional-painter",
    description: "Paint traditional Bhutanese motifs, patterns, and designs on buildings, monasteries, and furniture.",
    category: "Arts & Culture",
    industry: "Arts",
    riasecCode: "A",
    hollandCodes: ["A"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 12,000 - 25,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Traditional Patterns", "Freehand Painting", "Color Preparation", "Cultural Knowledge"],
    subjects: ["Art", "Cultural Studies"],
    workEnvironment: "Building, Workshop",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "brush",
    color: "#f97316",
  },
  {
    id: "career-weaver",
    title: "Weaver (Traditional Textiles)",
    name: "Weaver",
    slug: "weaver",
    description: "Weave traditional Bhutanese textiles including kira, bara, and other fabrics using backstrap loom or frame loom.",
    category: "Arts & Culture",
    industry: "Textile",
    riasecCode: "A",
    hollandCodes: ["A"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 10,000 - 25,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Weaving", "Pattern Design", "Color Combination", "Patience", "Creativity"],
    subjects: ["Art", "Mathematics"],
    workEnvironment: "Home, Weaving Center",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "frame",
    color: "#8b5cf6",
  },
  {
    id: "career-wood-carver",
    title: "Wood Carver",
    name: "Wood Carver",
    slug: "wood-carver",
    description: "Create traditional wood carvings for monasteries, buildings, and furniture. Intricate designs of dragons, flowers, and religious symbols.",
    category: "Arts & Culture",
    industry: "Handicraft",
    riasecCode: "RA",
    hollandCodes: ["R", "A"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 15,000 - 35,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Carving", "Design", "Patience", "Wood Knowledge", "Tool Handling"],
    subjects: ["Art", "Technical Drawing"],
    workEnvironment: "Workshop",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "scan",
    color: "#a16207",
  },
  {
    id: "career-statue-maker",
    title: "Statue Maker (Clay/Metal)",
    name: "Statue Maker",
    slug: "statue-maker",
    description: "Create Buddhist statues and sculptures using clay, metal, or other materials. Traditional craft for religious objects.",
    category: "Arts & Culture",
    industry: "Handicraft",
    riasecCode: "AR",
    hollandCodes: ["A", "R"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 15,000 - 40,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Sculpting", "Metal Work", "Iconography", "Patience", "Detail Orientation"],
    subjects: ["Art", "History"],
    workEnvironment: "Workshop",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "monument",
    color: "#d97706",
  },
  {
    id: "career-paper-maker",
    title: "Traditional Paper Maker",
    name: "Paper Maker",
    slug: "paper-maker",
    description: "Make traditional Bhutanese paper (deysho) from the bark of daphne plants. Handmade paper for religious texts and art.",
    category: "Arts & Culture",
    industry: "Handicraft",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "vocational",
    typicalSalary: "Nu. 10,000 - 20,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "low",
    skills: ["Paper Making", "Boiling", "Drying", "Quality Control"],
    subjects: ["Chemistry"],
    workEnvironment: "Workshop",
    bhutanSpecific: true,
    bhutanDemand: "low",
    rubPrograms: [],
    icon: "scroll",
    color: "#fef3c7",
  },
];

// ============================================================================
// SERVICE & HOSPITALITY
// ============================================================================

const SERVICE_CAREERS = [
  {
    id: "career-tour-guide",
    title: "Tour Guide",
    name: "Tour Guide",
    slug: "tour-guide",
    description: "Guide tourists through Bhutan's cultural sites, monasteries, and natural attractions. Share knowledge about Bhutanese culture and history.",
    category: "Tourism",
    industry: "Tourism",
    riasecCode: "S",
    hollandCodes: ["S"],
    educationLevel: "class12",
    typicalSalary: "Nu. 15,000 - 35,000/month + tips",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Public Speaking", "History", "Cultural Knowledge", "Languages", "Customer Service"],
    subjects: ["History", "English", "Dzongkha"],
    workEnvironment: "Tourist Sites, Outdoor",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "rtc", programId: "cert-tourism", programName: "Certificate in Tourism at RTC" },
    ],
    icon: "map",
    color: "#10b981",
  },
  {
    id: "career-hotel-receptionist",
    title: "Hotel Receptionist",
    name: "Hotel Receptionist",
    slug: "hotel-receptionist",
    description: "Welcome guests, manage check-ins/check-outs, handle reservations, and provide information about hotel services.",
    category: "Tourism",
    industry: "Hospitality",
    riasecCode: "CS",
    hollandCodes: ["C", "S"],
    educationLevel: "class12",
    typicalSalary: "Nu. 12,000 - 22,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Customer Service", "Computer Skills", "Communication", "Multitasking", "English"],
    subjects: ["English", "Computer Applications", "Mathematics"],
    workEnvironment: "Hotel",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "bell",
    color: "#8b5cf6",
  },
  {
    id: "career-housekeeping",
    title: "Housekeeping Staff",
    name: "Housekeeping Staff",
    slug: "housekeeping",
    description: "Maintain cleanliness and order in hotels, hospitals, and offices. Clean rooms, change linens, and ensure hygiene standards.",
    category: "Tourism",
    industry: "Hospitality",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 18,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Cleaning", "Attention to Detail", "Physical Stamina", "Time Management"],
    subjects: [],
    workEnvironment: "Hotel, Hospital, Office",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "sparkles",
    color: "#06b6d4",
  },
  {
    id: "career-waiter",
    title: "Waiter/Waitress",
    name: "Wait Staff",
    slug: "waiter",
    description: "Serve food and drinks in restaurants and hotels. Take orders, serve meals, and ensure customer satisfaction.",
    category: "Tourism",
    industry: "Hospitality",
    riasecCode: "S",
    hollandCodes: ["S"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 20,000/month + tips",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Customer Service", "Communication", "Teamwork", "Basic Math"],
    subjects: ["English", "Mathematics"],
    workEnvironment: "Restaurant, Hotel",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "utensils",
    color: "#f59e0b",
  },
  {
    id: "career-cook-helper",
    title: "Cook Helper",
    name: "Cook Helper",
    slug: "cook-helper",
    description: "Assist chefs in kitchen preparation. Learn cooking skills and advance to chef position. Work in restaurants and hotels.",
    category: "Tourism",
    industry: "Hospitality",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 18,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Food Preparation", "Kitchen Safety", "Cleanliness", "Following Recipes"],
    subjects: [],
    workEnvironment: "Kitchen",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "chef-hat",
    color: "#dc2626",
  },
];

// ============================================================================
// AGRICULTURE & FARMING
// ============================================================================

const AGRICULTURE_CAREERS = [
  {
    id: "career-farmer",
    title: "Farmer (Commercial/Subsistence)",
    name: "Farmer",
    slug: "farmer",
    description: "Cultivate crops and manage agricultural land. Grow rice, wheat, vegetables, or fruits. Can be self-employed.",
    category: "Agriculture",
    industry: "Agriculture",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 8,000 - 25,000/month (varies)",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Farming", "Irrigation", "Pest Control", "Seasonal Planning", "Physical Labor"],
    subjects: ["Agriculture", "Biology"],
    workEnvironment: "Farm, Field",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "cnr", programId: "diploma-agri", programName: "Diploma in Agriculture at CNR" },
    ],
    icon: "wheat",
    color: "#22c55e",
  },
  {
    id: "career-dairy-farmer",
    title: "Dairy Farmer",
    name: "Dairy Farmer",
    slug: "dairy-farmer",
    description: "Raise cattle for milk production. Manage animal health, milking, and dairy product processing.",
    category: "Agriculture",
    industry: "Livestock",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 12,000 - 30,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Animal Care", "Milking", "Feeding", "Basic Veterinary"],
    subjects: ["Biology", "Agriculture"],
    workEnvironment: "Farm",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "cow",
    color: "#f5f5f4",
  },
  {
    id: "career-livestock-worker",
    title: "Livestock Worker",
    name: "Livestock Worker",
    slug: "livestock-worker",
    description: "Care for animals including cattle, pigs, poultry, and yaks. Feed, clean, and monitor animal health.",
    category: "Agriculture",
    industry: "Livestock",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 20,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Animal Care", "Feeding", "Cleaning", "Physical Stamina"],
    subjects: ["Biology"],
    workEnvironment: "Farm",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "paw-print",
    color: "#78716c",
  },
  {
    id: "career-gardener",
    title: "Gardener/Landscaper",
    name: "Gardener",
    slug: "gardener",
    description: "Maintain gardens, parks, and landscapes. Plant flowers, trim trees, and care for outdoor spaces.",
    category: "Agriculture",
    industry: "Horticulture",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 18,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Planting", "Pruning", "Lawn Care", "Tool Use"],
    subjects: ["Biology"],
    workEnvironment: "Garden, Park",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "leaf",
    color: "#22c55e",
  },
  {
    id: "career-agriculture-labour",
    title: "Agriculture Labour",
    name: "Agriculture Labour",
    slug: "agriculture-labour",
    description: "Work on farms during planting and harvesting seasons. Perform manual labour tasks in agricultural fields.",
    category: "Agriculture",
    industry: "Agriculture",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 500 - 800/day (seasonal)",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Physical Stamina", "Field Work", "Teamwork"],
    subjects: [],
    workEnvironment: "Farm Field",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "sun",
    color: "#fbbf24",
  },
];

// ============================================================================
// RETAIL & SALES
// ============================================================================

const RETAIL_CAREERS = [
  {
    id: "career-shop-assistant",
    title: "Shop Assistant",
    name: "Shop Assistant",
    slug: "shop-assistant",
    description: "Work in retail stores selling groceries, clothes, electronics, or other goods. Assist customers, stock shelves, and handle payments.",
    category: "Retail",
    industry: "Retail",
    riasecCode: "S",
    hollandCodes: ["S"],
    educationLevel: "class12",
    typicalSalary: "Nu. 10,000 - 18,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Customer Service", "Cash Handling", "Communication", "Product Knowledge"],
    subjects: ["Mathematics", "English"],
    workEnvironment: "Retail Store",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "shopping-cart",
    color: "#3b82f6",
  },
  {
    id: "career-sales-representative",
    title: "Sales Representative",
    name: "Sales Representative",
    slug: "sales-representative",
    description: "Sell products for companies including insurance, real estate, consumer goods. Earn commissions based on sales.",
    category: "Retail",
    industry: "Sales",
    riasecCode: "E",
    hollandCodes: ["E"],
    educationLevel: "class12",
    typicalSalary: "Nu. 12,000 - 30,000/month + commission",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Communication", "Persuasion", "Product Knowledge", "Customer Relations"],
    subjects: ["English", "Mathematics"],
    workEnvironment: "Office, Field",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "percent",
    color: "#10b981",
  },
  {
    id: "career-small-shop-owner",
    title: "Small Shop Owner",
    name: "Small Shop Owner",
    slug: "small-shop-owner",
    description: "Run own small business - grocery shop, stationary, hardware, or café. Self-employment opportunity in towns and villages.",
    category: "Business",
    industry: "Small Business",
    riasecCode: "E",
    hollandCodes: ["E"],
    educationLevel: "class10",
    typicalSalary: "Nu. 15,000 - 50,000/month (varies)",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Business Management", "Customer Service", "Accounting", "Inventory"],
    subjects: ["Mathematics", "Business Studies"],
    workEnvironment: "Own Shop",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "store",
    color: "#f59e0b",
  },
  {
    id: "career-street-vendor",
    title: "Street Vendor",
    name: "Street Vendor",
    slug: "street-vendor",
    description: "Sell goods on street - vegetables, momos, snacks, clothes. Low capital self-employment option.",
    category: "Business",
    industry: "Small Business",
    riasecCode: "E",
    hollandCodes: ["E"],
    educationLevel: "class10",
    typicalSalary: "Nu. 8,000 - 20,000/month (varies)",
    salaryCurrency: "BTN",
    growthOutlook: "low",
    skills: ["Sales", "Product Preparation", "Customer Interaction"],
    subjects: [],
    workEnvironment: "Street, Market",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "truck",
    color: "#ef4444",
  },
];

// ============================================================================
// TRANSPORTATION & LOGISTICS
// ============================================================================

const TRANSPORT_CAREERS = [
  {
    id: "career-truck-driver",
    title: "Truck Driver",
    name: "Truck Driver",
    slug: "truck-driver",
    description: "Drive trucks to transport goods across Bhutan. Long-distance driving between towns and cities.",
    category: "Transportation",
    industry: "Logistics",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 15,000 - 30,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Heavy Vehicle Driving", "Route Planning", "Vehicle Maintenance", "Safety"],
    subjects: [],
    workEnvironment: "Road, Highway",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "truck",
    color: "#64748b",
  },
  {
    id: "career-bus-driver",
    title: "Bus Driver",
    name: "Bus Driver",
    slug: "bus-driver",
    description: "Drive buses for public transport or private companies. Transport passengers safely on scheduled routes.",
    category: "Transportation",
    industry: "Public Transport",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 12,000 - 25,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Bus Driving", "Customer Service", "Safety", "Route Knowledge"],
    subjects: [],
    workEnvironment: "Bus, Road",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "bus",
    color: "#fbbf24",
  },
  {
    id: "career-delivery-person",
    title: "Delivery Person",
    name: "Delivery Person",
    slug: "delivery-person",
    description: "Deliver parcels, food, and goods to customers. Work for courier companies or food delivery services.",
    category: "Transportation",
    industry: "Logistics",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 20,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Navigation", "Customer Service", "Time Management", "Two-wheeler Driving"],
    subjects: [],
    workEnvironment: "Road, City",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "package",
    color: "#3b82f6",
  },
];

// ============================================================================
// SECURITY & PROTECTION
// ============================================================================

const SECURITY_CAREERS = [
  {
    id: "career-security-guard",
    title: "Security Guard",
    name: "Security Guard",
    slug: "security-guard",
    description: "Provide security for buildings, banks, shops, and events. Monitor access and maintain safety.",
    category: "Security",
    industry: "Security Services",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 10,000 - 18,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Observation", "Report Writing", "Physical Fitness", "Communication"],
    subjects: ["English"],
    workEnvironment: "Office, Bank, Building",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "shield",
    color: "#6b7280",
  },
  {
    id: "career-bntp-officer",
    title: "Royal Bhutan Police (Constable)",
    name: "Police Constable",
    slug: "police-constable",
    description: "Maintain law and order, prevent crime, and protect citizens. Entry-level position in Royal Bhutan Police.",
    category: "Security",
    industry: "Government",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class12",
    typicalSalary: "Nu. 18,000 - 25,000/month + benefits",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Physical Fitness", "Discipline", "Law Knowledge", "Communication"],
    subjects: ["English", "Legal Studies"],
    workEnvironment: "Police Station, Field",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "badge",
    color: "#1e40af",
  },
];

// ============================================================================
// MEDIA & COMMUNICATIONS
// ============================================================================

const MEDIA_CAREERS = [
  {
    id: "career-photographer",
    title: "Photographer",
    name: "Photographer",
    slug: "photographer",
    description: "Take photographs for events, weddings, news, or tourism. Can be freelance or work for studios/companies.",
    category: "Media",
    industry: "Media",
    riasecCode: "A",
    hollandCodes: ["A"],
    educationLevel: "class12",
    typicalSalary: "Nu. 12,000 - 30,000/month (freelance varies)",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Photography", "Editing", "Composition", "Equipment Handling"],
    subjects: ["Art", "IT"],
    workEnvironment: "Studio, Outdoor, Events",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "camera",
    color: "#6366f1",
  },
  {
    id: "career-video-editor",
    title: "Video Editor",
    name: "Video Editor",
    slug: "video-editor",
    description: "Edit videos for social media, TV, or productions. Use editing software to create engaging content.",
    category: "Media",
    industry: "Media",
    riasecCode: "A",
    hollandCodes: ["A"],
    educationLevel: "class12",
    typicalSalary: "Nu. 15,000 - 35,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Video Editing", "Premiere Pro", "After Effects", "Storytelling"],
    subjects: ["IT", "Art"],
    workEnvironment: "Studio, Office",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "film",
    color: "#8b5cf6",
  },
];

// ============================================================================
// BANKING & FINANCE (Entry Level)
// ============================================================================

const BANKING_CAREERS = [
  {
    id: "career-bank-teller",
    title: "Bank Teller",
    name: "Bank Teller",
    slug: "bank-teller",
    description: "Handle customer transactions at banks including deposits, withdrawals, and account inquiries. Entry-level banking position.",
    category: "Banking",
    industry: "Finance",
    riasecCode: "C",
    hollandCodes: ["C"],
    educationLevel: "class12",
    typicalSalary: "Nu. 15,000 - 25,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Cash Handling", "Customer Service", "Basic Accounting", "Computer Skills"],
    subjects: ["Mathematics", "English", "Accounting"],
    workEnvironment: "Bank",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "landmark",
    color: "#10b981",
  },
];

// ============================================================================
// CALL CENTER & CUSTOMER SERVICE
// ============================================================================

const CALL_CENTER_CAREERS = [
  {
    id: "career-call-center-agent",
    title: "Call Center Agent",
    name: "Call Center Agent",
    slug: "call-center-agent",
    description: "Handle incoming and outgoing calls for customer service, sales, or support. Work for telecom, banks, or service companies.",
    category: "Customer Service",
    industry: "BPO",
    riasecCode: "S",
    hollandCodes: ["S"],
    educationLevel: "class12",
    typicalSalary: "Nu. 12,000 - 22,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Communication", "English", "Dzongkha", "Problem Solving", "Typing"],
    subjects: ["English", "Computer Skills"],
    workEnvironment: "Office",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "phone",
    color: "#3b82f6",
  },
];

// ============================================================================
// CONSTRUCTION LABOR
// ============================================================================

const CONSTRUCTION_CAREERS = [
  {
    id: "career-construction-labour",
    title: "Construction Labour",
    name: "Construction Labour",
    slug: "construction-labour",
    description: "General labour at construction sites. Carry materials, dig, mix concrete, and assist skilled workers.",
    category: "Construction",
    industry: "Construction",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "class10",
    typicalSalary: "Nu. 500 - 900/day",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Physical Stamina", "Following Instructions", "Teamwork"],
    subjects: [],
    workEnvironment: "Construction Site",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [],
    icon: "hard-hat",
    color: "#f97316",
  },
];

// ============================================================================
// PERSONAL SERVICES
// ============================================================================

const PERSONAL_SERVICE_CAREERS = [
  {
    id: "career-barber",
    title: "Barber/Hairdresser",
    name: "Barber",
    slug: "barber",
    description: "Cut and style hair. Can run own barber shop or work in salons. Self-employment option.",
    category: "Personal Services",
    industry: "Personal Care",
    riasecCode: "A",
    hollandCodes: ["A"],
    educationLevel: "class10",
    typicalSalary: "Nu. 12,000 - 30,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Hair Cutting", "Styling", "Customer Service", "Tool Handling"],
    subjects: [],
    workEnvironment: "Salon, Shop",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "scissors",
    color: "#6b7280",
  },
  {
    id: "career-beautician",
    title: "Beautician",
    name: "Beautician",
    slug: "beautician",
    description: "Provide beauty services including makeup, facials, and skincare. Work in salons or run own business.",
    category: "Personal Services",
    industry: "Beauty",
    riasecCode: "A",
    hollandCodes: ["A"],
    educationLevel: "class12",
    typicalSalary: "Nu. 15,000 - 35,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Makeup", "Skincare", "Customer Service", "Product Knowledge"],
    subjects: ["Biology"],
    workEnvironment: "Salon",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "sparkle",
    color: "#ec4899",
  },
];

// ============================================================================
// COMBINE ALL CAREERS
// ============================================================================

const ALL_CAREERS = [
  ...GOVERNMENT_CAREERS,
  ...TRADE_CAREERS,
  ...ARTS_CAREERS,
  ...SERVICE_CAREERS,
  ...AGRICULTURE_CAREERS,
  ...RETAIL_CAREERS,
  ...TRANSPORT_CAREERS,
  ...SECURITY_CAREERS,
  ...MEDIA_CAREERS,
  ...BANKING_CAREERS,
  ...CALL_CENTER_CAREERS,
  ...CONSTRUCTION_CAREERS,
  ...PERSONAL_SERVICE_CAREERS,
];

// ============================================================================
// DATABASE SEEDING FUNCTION
// ============================================================================

async function seedCareers() {
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL environment variable is not set");
  }

  console.log("🌱 Seeding diverse careers for Bhutan's students...");
  console.log(`📊 Total careers to seed: ${ALL_CAREERS.length}`);

  let inserted = 0;
  let updated = 0;
  let errors = 0;

  for (const career of ALL_CAREERS) {
    try {
      // Check if career exists
      const existing = await db
        .select()
        .from(careers)
        .where(eq(careers.id, career.id))
        .limit(1);

      if (existing.length > 0) {
        // Update existing
        await db
          .update(careers)
          .set({
            ...career,
            updatedAt: new Date(),
          })
          .where(eq(careers.id, career.id));
        updated++;
        console.log(`  ✏️  Updated: ${career.title}`);
      } else {
        // Insert new
        await db.insert(careers).values({
          ...career,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        });
        inserted++;
        console.log(`  ✅ Inserted: ${career.title}`);
      }
    } catch (error) {
      errors++;
      console.error(`  ❌ Error with ${career.title}:`, error);
    }
  }

  console.log("\n" + "=".repeat(50));
  console.log("📈 SEEDING SUMMARY");
  console.log("=".repeat(50));
  console.log(`✅ Inserted: ${inserted} new careers`);
  console.log(`✏️  Updated: ${updated} existing careers`);
  console.log(`❌ Errors: ${errors}`);
  console.log(`📊 Total careers processed: ${inserted + updated}`);
  console.log("=".repeat(50));
}

// ============================================================================
// RUN SEEDING
// ============================================================================

seedCareers()
  .then(() => {
    console.log("\n✨ Diverse careers seeded successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("\n❌ Error seeding careers:", error);
    process.exit(1);
  });
