/**
 * SEED CAREERS DATABASE
 *
 * Populates the careers table with comprehensive career options
 * relevant to Bhutanese students, including:
 * - Local career opportunities
 * - Regional career paths
 * - Study abroad options
 * - RIASEC Holland Code mappings
 * - Education requirements
 * - Salary information
 *
 * Run: npx tsx scripts/seed-careers.ts
 */

import "dotenv/config";
import { db } from "@/lib/db";
import { careers } from "@/lib/db/schema";
import { nanoid } from "nanoid";
import { eq } from "drizzle-orm";

// ============================================================================
// COMPREHENSIVE CAREERS DATA
// ============================================================================

const CAREERS_DATA = [
  // ============================================================================
  // TECHNOLOGY & ENGINEERING (R, I, E)
  // ============================================================================
  {
    id: "career-software-developer",
    title: "Software Developer",
    name: "Software Developer",
    slug: "software-developer",
    description: "Design and create software applications and systems. Work with programming languages to build websites, mobile apps, and software solutions.",
    category: "Technology",
    industry: "Technology",
    riasecCode: "IRC",
    hollandCodes: ["I", "R", "C"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 30,000 - 80,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "very-high",
    skills: ["Programming", "Problem Solving", "Logic", "Mathematics", "Debugging"],
    subjects: ["Mathematics", "Computer Science", "Physics"],
    workEnvironment: "Office, Remote, Hybrid",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "gcit", programId: "bca", programName: "B.C.A at GCIT" },
      { collegeId: "cst", programId: "bsc-cs", programName: "B.Sc. Computer Science at CST" },
    ],
    icon: "laptop",
    color: "#3b82f6",
  },
  {
    id: "career-data-analyst",
    title: "Data Analyst",
    name: "Data Analyst",
    slug: "data-analyst",
    description: "Analyze data to help businesses make informed decisions. Create reports, dashboards, and insights from complex datasets.",
    category: "Technology",
    industry: "Technology",
    riasecCode: "ICR",
    hollandCodes: ["I", "C", "R"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 35,000 - 90,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "very-high",
    skills: ["Statistics", "Excel", "SQL", "Critical Thinking", "Data Visualization"],
    subjects: ["Mathematics", "Statistics", "Computer Science", "Economics"],
    workEnvironment: "Office, Remote",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "gcit", programId: "bsc-it", programName: "B.Sc. IT at GCIT" },
    ],
    icon: "bar-chart",
    color: "#06b6d4",
  },
  {
    id: "career-civil-engineer",
    title: "Civil Engineer",
    name: "Civil Engineer",
    slug: "civil-engineer",
    description: "Design and build infrastructure like roads, bridges, buildings, and water systems. Essential for Bhutan's development.",
    category: "Engineering",
    industry: "Construction",
    riasecCode: "RIE",
    hollandCodes: ["R", "I", "E"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 25,000 - 60,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Design", "Construction Knowledge", "Project Management", "AutoCAD", "Surveying"],
    subjects: ["Mathematics", "Physics", "Chemistry"],
    workEnvironment: "Office, Field, Site",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "cst", programId: "be-civil", programName: "B.E. Civil at CST" },
      { collegeId: "jnec", programId: "be-civil", programName: "B.E. Civil at JNEC" },
    ],
    icon: "building",
    color: "#f59e0b",
  },
  {
    id: "career-electrical-engineer",
    title: "Electrical Engineer",
    name: "Electrical Engineer",
    slug: "electrical-engineer",
    description: "Design and develop electrical systems for power generation, distribution, and equipment. Critical for Bhutan's hydropower sector.",
    category: "Engineering",
    industry: "Energy",
    riasecCode: "RI",
    hollandCodes: ["R", "I"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 30,000 - 70,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Circuit Design", "Power Systems", "Safety Protocols", "Problem Solving"],
    subjects: ["Mathematics", "Physics", "Chemistry"],
    workEnvironment: "Office, Field, Power Plant",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "cst", programId: "be-electrical", programName: "B.E. Electrical at CST" },
      { collegeId: "jnec", programId: "be-electrical", programName: "B.E. Electrical at JNEC" },
    ],
    icon: "zap",
    color: "#eab308",
  },
  {
    id: "career-it-support-specialist",
    title: "IT Support Specialist",
    name: "IT Support Specialist",
    slug: "it-support-specialist",
    description: "Provide technical support for computer systems, networks, and software. Help organizations maintain their IT infrastructure.",
    category: "Technology",
    industry: "Technology",
    riasecCode: "RCI",
    hollandCodes: ["R", "C", "I"],
    educationLevel: "diploma",
    typicalSalary: "Nu. 15,000 - 35,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Troubleshooting", "Networking", "Customer Service", "Hardware Repair"],
    subjects: ["Computer Science", "Mathematics"],
    workEnvironment: "Office, Data Center",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "gcit", programId: "diploma-it", programName: "Diploma in IT at GCIT" },
      { collegeId: "tti-thimphu", programId: "cert-ict", programName: "Certificate in ICT at TTI" },
    ],
    icon: "monitor",
    color: "#8b5cf6",
  },

  // ============================================================================
  // HEALTHCARE & MEDICAL (I, S, R)
  // ============================================================================
  {
    id: "career-nurse",
    title: "Nurse",
    name: "Nurse",
    slug: "nurse",
    description: "Provide healthcare and support to patients in hospitals, clinics, and community health centers. Critical for Bhutan's healthcare system.",
    category: "Healthcare",
    industry: "Healthcare",
    riasecCode: "SIR",
    hollandCodes: ["S", "I", "R"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 20,000 - 50,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "very-high",
    skills: ["Medical Knowledge", "Empathy", "Attention to Detail", "Communication", "Patient Care"],
    subjects: ["Biology", "Chemistry", "English"],
    workEnvironment: "Hospital, Clinic, Community Center",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "rtc", programId: "bsc-nursing", programName: "B.Sc. Nursing at RTC" },
    ],
    icon: "heart-pulse",
    color: "#ef4444",
  },
  {
    id: "career-doctor",
    title: "Doctor (Physician)",
    name: "Doctor",
    slug: "doctor",
    description: "Diagnose and treat illnesses, prescribe medications, and provide medical care to patients. Requires medical school and residency.",
    category: "Healthcare",
    industry: "Healthcare",
    riasecCode: "ISR",
    hollandCodes: ["I", "S", "R"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 40,000 - 100,000+/month",
    salaryCurrency: "BTN",
    growthOutlook: "very-high",
    skills: ["Medical Diagnosis", "Patient Care", "Communication", "Critical Thinking"],
    subjects: ["Biology", "Chemistry", "Physics", "Mathematics"],
    workEnvironment: "Hospital, Clinic",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [],
    icon: "stethoscope",
    color: "#dc2626",
  },
  {
    id: "career-pharmacist",
    title: "Pharmacist",
    name: "Pharmacist",
    slug: "pharmacist",
    description: "Dispense medications, advise patients on proper drug use, and work with healthcare providers on drug therapies.",
    category: "Healthcare",
    industry: "Healthcare",
    riasecCode: "ISC",
    hollandCodes: ["I", "S", "C"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 25,000 - 60,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Pharmacology", "Attention to Detail", "Customer Service", "Medication Knowledge"],
    subjects: ["Biology", "Chemistry", "Mathematics"],
    workEnvironment: "Pharmacy, Hospital",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "pill",
    color: "#f97316",
  },
  {
    id: "career-public-health-officer",
    title: "Public Health Officer",
    name: "Public Health Officer",
    slug: "public-health-officer",
    description: "Work on community health initiatives, disease prevention, and health education programs.",
    category: "Healthcare",
    industry: "Healthcare",
    riasecCode: "SIE",
    hollandCodes: ["S", "I", "E"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 20,000 - 50,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Health Education", "Community Outreach", "Data Analysis", "Program Management"],
    subjects: ["Biology", "Chemistry", "English"],
    workEnvironment: "Office, Community",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "rtc", programId: "bsc-public-health", programName: "B.Sc. Public Health at RTC" },
    ],
    icon: "users",
    color: "#10b981",
  },

  // ============================================================================
  // EDUCATION & TEACHING (S, A, I)
  // ============================================================================
  {
    id: "career-teacher",
    title: "Teacher",
    name: "Teacher",
    slug: "teacher",
    description: "Educate and inspire students in various subjects. Teach at primary, secondary, or higher secondary levels.",
    category: "Education",
    industry: "Education",
    riasecCode: "SIA",
    hollandCodes: ["S", "I", "A"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 15,000 - 40,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Communication", "Patience", "Subject Knowledge", "Presentation", "Classroom Management"],
    subjects: ["Varies by subject taught"],
    workEnvironment: "School",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "pce", programId: "bed-primary", programName: "B.Ed Primary at PCE" },
      { collegeId: "pce", programId: "bed-secondary", programName: "B.Ed Secondary at PCE" },
      { collegeId: "sce", programId: "bed-primary", programName: "B.Ed Primary at SCE" },
      { collegeId: "sce", programId: "bed-secondary", programName: "B.Ed Secondary at SCE" },
    ],
    icon: "graduation-cap",
    color: "#0ea5e9",
  },
  {
    id: "career-counselor",
    title: "School Counselor",
    name: "School Counselor",
    slug: "school-counselor",
    description: "Guide students in academic, career, and personal development. Provide counseling and support services.",
    category: "Education",
    industry: "Education",
    riasecCode: "SAI",
    hollandCodes: ["S", "A", "I"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 20,000 - 45,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Active Listening", "Empathy", "Guidance", "Communication", "Psychology"],
    subjects: ["Psychology", "Education", "English"],
    workEnvironment: "School",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "sce", programId: "pgd-gc", programName: "PG Diploma in Guidance & Counseling at SCE" },
    ],
    icon: "message-circle",
    color: "#8b5cf6",
  },
  {
    id: "career-principal",
    title: "School Principal",
    name: "School Principal",
    slug: "school-principal",
    description: "Lead and manage schools, oversee curriculum implementation, manage staff, and ensure quality education.",
    category: "Education",
    industry: "Education",
    riasecCode: "ESA",
    hollandCodes: ["E", "S", "A"],
    educationLevel: "master",
    typicalSalary: "Nu. 35,000 - 70,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Leadership", "Management", "Communication", "Educational Administration"],
    subjects: ["Education", "Management"],
    workEnvironment: "School Office",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [
      { collegeId: "pce", programId: "med-leadership", programName: "M.Ed. Educational Leadership at PCE" },
    ],
    icon: "building-2",
    color: "#6366f1",
  },

  // ============================================================================
  // BUSINESS & FINANCE (E, C, S)
  // ============================================================================
  {
    id: "career-accountant",
    title: "Accountant",
    name: "Accountant",
    slug: "accountant",
    description: "Manage financial records, prepare financial statements, and ensure tax compliance for organizations.",
    category: "Finance",
    industry: "Finance",
    riasecCode: "CEI",
    hollandCodes: ["C", "E", "I"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 20,000 - 60,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Accounting", "Attention to Detail", "Mathematics", "Financial Software", "Taxation"],
    subjects: ["Mathematics", "Economics", "Business Studies", "Accountancy"],
    workEnvironment: "Office",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "gcbs", programId: "bcom", programName: "B.Com at GCBS" },
      { collegeId: "sherubtse", programId: "bcom", programName: "B.Com at Sherubtse" },
    ],
    icon: "calculator",
    color: "#059669",
  },
  {
    id: "career-financial-analyst",
    title: "Financial Analyst",
    name: "Financial Analyst",
    slug: "financial-analyst",
    description: "Analyze financial data, provide investment recommendations, and help businesses make financial decisions.",
    category: "Finance",
    industry: "Finance",
    riasecCode: "ICE",
    hollandCodes: ["I", "C", "E"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 30,000 - 80,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Financial Analysis", "Excel", "Modeling", "Market Research"],
    subjects: ["Mathematics", "Economics", "Business Studies"],
    workEnvironment: "Office",
    bhutanSpecific: false,
    bhutanDemand: "medium",
    rubPrograms: [
      { collegeId: "gcbs", programId: "bba-finance", programName: "B.B.A Finance at GCBS" },
    ],
    icon: "trending-up",
    color: "#10b981",
  },
  {
    id: "career-marketing-manager",
    title: "Marketing Manager",
    name: "Marketing Manager",
    slug: "marketing-manager",
    description: "Develop marketing strategies, manage campaigns, and promote products or services to target audiences.",
    category: "Business",
    industry: "Marketing",
    riasecCode: "EAS",
    hollandCodes: ["E", "A", "S"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 25,000 - 70,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Communication", "Creativity", "Market Research", "Digital Marketing"],
    subjects: ["English", "Business Studies", "Economics", "Media Studies"],
    workEnvironment: "Office",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [
      { collegeId: "gcbs", programId: "bba-marketing", programName: "B.B.A Marketing at GCBS" },
    ],
    icon: "megaphone",
    color: "#f43f5e",
  },
  {
    id: "career-hr-manager",
    title: "Human Resources Manager",
    name: "HR Manager",
    slug: "hr-manager",
    description: "Manage employee recruitment, training, compensation, and workplace policies for organizations.",
    category: "Business",
    industry: "Human Resources",
    riasecCode: "SEC",
    hollandCodes: ["S", "E", "C"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 25,000 - 60,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Communication", "Conflict Resolution", "Recruitment", "Labor Laws"],
    subjects: ["Business Studies", "Psychology", "English"],
    workEnvironment: "Office",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [
      { collegeId: "gcbs", programId: "bba", programName: "B.B.A at GCBS" },
    ],
    icon: "users-round",
    color: "#6366f1",
  },

  // ============================================================================
  // AGRICULTURE & NATURAL RESOURCES (R, I, E)
  // ============================================================================
  {
    id: "career-agriculturist",
    title: "Agriculturist",
    name: "Agriculturist",
    slug: "agriculturist",
    description: "Work in farming, agricultural research, or agribusiness. Improve crop yields and farming practices.",
    category: "Agriculture",
    industry: "Agriculture",
    riasecCode: "RIE",
    hollandCodes: ["R", "I", "E"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 15,000 - 40,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Farming Knowledge", "Business", "Research", "Sustainability", "Crop Management"],
    subjects: ["Biology", "Chemistry", "Economics"],
    workEnvironment: "Farm, Office, Field",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "cnr", programId: "bsc-agri", programName: "B.Sc. Agriculture at CNR" },
      { collegeId: "cnr", programId: "diploma-agri", programName: "Diploma in Agriculture at CNR" },
    ],
    icon: "sprout",
    color: "#22c55e",
  },
  {
    id: "career-forestry-officer",
    title: "Forestry Officer",
    name: "Forestry Officer",
    slug: "forestry-officer",
    description: "Manage and protect forest resources, implement conservation programs, and promote sustainable forestry.",
    category: "Agriculture",
    industry: "Forestry",
    riasecCode: "RI",
    hollandCodes: ["R", "I"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 20,000 - 50,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Forest Management", "Conservation", "Field Work", "Environmental Science"],
    subjects: ["Biology", "Chemistry", "Geography"],
    workEnvironment: "Forest, Office, Field",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "cnr", programId: "bsc-forestry", programName: "B.Sc. Forestry at CNR" },
      { collegeId: "cnr", programId: "diploma-forestry", programName: "Diploma in Forestry at CNR" },
    ],
    icon: "trees",
    color: "#16a34a",
  },
  {
    id: "career-livestock-officer",
    title: "Livestock Officer",
    name: "Livestock Officer",
    slug: "livestock-officer",
    description: "Work in animal husbandry, veterinary services, or livestock management for improved agricultural productivity.",
    category: "Agriculture",
    industry: "Agriculture",
    riasecCode: "RIS",
    hollandCodes: ["R", "I", "S"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 18,000 - 45,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Animal Care", "Veterinary Basics", "Farm Management", "Breeding"],
    subjects: ["Biology", "Chemistry"],
    workEnvironment: "Farm, Office",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "cnr", programId: "bsc-animal", programName: "B.Sc. Animal Science at CNR" },
      { collegeId: "cnr", programId: "diploma-animal", programName: "Diploma in Animal Husbandry at CNR" },
    ],
    icon: "paw-print",
    color: "#a3e635",
  },
  {
    id: "career-environmental-scientist",
    title: "Environmental Scientist",
    name: "Environmental Scientist",
    slug: "environmental-scientist",
    description: "Study environmental issues, develop solutions for pollution and climate change, and promote sustainability.",
    category: "Science",
    industry: "Environment",
    riasecCode: "IIR",
    hollandCodes: ["I", "R"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 25,000 - 60,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "very-high",
    skills: ["Environmental Science", "Data Analysis", "Research", "Policy Knowledge"],
    subjects: ["Biology", "Chemistry", "Physics", "Geography"],
    workEnvironment: "Field, Laboratory, Office",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "cnr", programId: "bsc-environment", programName: "B.Sc. Environment & Climate at CNR" },
    ],
    icon: "leaf",
    color: "#84cc16",
  },

  // ============================================================================
  // ARTS, CULTURE & MEDIA (A, S, E)
  // ============================================================================
  {
    id: "career-graphic-designer",
    title: "Graphic Designer",
    name: "Graphic Designer",
    slug: "graphic-designer",
    description: "Create visual content for brands, marketing materials, and communications using design software.",
    category: "Arts",
    industry: "Design",
    riasecCode: "AIR",
    hollandCodes: ["A", "I", "R"],
    educationLevel: "diploma",
    typicalSalary: "Nu. 15,000 - 50,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Design Software", "Creativity", "Color Theory", "Typography", "Branding"],
    subjects: ["Art", "Computer Science", "English"],
    workEnvironment: "Office, Studio, Freelance",
    bhutanSpecific: false,
    bhutanDemand: "medium",
    rubPrograms: [],
    icon: "palette",
    color: "#ec4899",
  },
  {
    id: "career-journalist",
    title: "Journalist",
    name: "Journalist",
    slug: "journalist",
    description: "Report news, write stories, and inform the public through print, broadcast, or digital media.",
    category: "Media",
    industry: "Media",
    riasecCode: "ASE",
    hollandCodes: ["A", "S", "E"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 18,000 - 50,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Writing", "Research", "Interviewing", "Critical Thinking"],
    subjects: ["English", "Dzongkha", "Social Studies"],
    workEnvironment: "Office, Field",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [
      { collegeId: "sherubtse", programId: "ba", programName: "B.A. at Sherubtse" },
      { collegeId: "rtc", programId: "ba-political-science", programName: "B.A. Political Science at RTC" },
    ],
    icon: "newspaper",
    color: "#64748b",
  },
  {
    id: "career-language-specialist",
    title: "Language & Culture Specialist",
    name: "Language & Culture Specialist",
    slug: "language-culture-specialist",
    description: "Preserve and promote Bhutanese language, culture, and traditions. Work in cultural institutions or education.",
    category: "Arts",
    industry: "Culture",
    riasecCode: "ASI",
    hollandCodes: ["A", "S", "I"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 18,000 - 45,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Dzongkha", "Teaching", "Cultural Knowledge", "Research"],
    subjects: ["Dzongkha", "English", "History"],
    workEnvironment: "Office, School, Cultural Center",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "clcs", programId: "ba-language-culture", programName: "B.A. Language & Culture at CLCS" },
      { collegeId: "sherubtse", programId: "ba-history-dzongkha", programName: "B.A. History & Dzongkha at Sherubtse" },
    ],
    icon: "book-open",
    color: "#d97706",
  },

  // ============================================================================
  // VOCATIONAL & TECHNICAL (R, I, C)
  // ============================================================================
  {
    id: "career-auto-mechanic",
    title: "Automobile Mechanic",
    name: "Automobile Mechanic",
    slug: "automobile-mechanic",
    description: "Repair and maintain vehicles, diagnose problems, and perform routine maintenance on cars and trucks.",
    category: "Vocational",
    industry: "Automotive",
    riasecCode: "RI",
    hollandCodes: ["R", "I"],
    educationLevel: "certificate",
    typicalSalary: "Nu. 12,000 - 35,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Mechanical Skills", "Diagnostic Tools", "Problem Solving", "Customer Service"],
    subjects: ["Physics", "Mathematics", "Technical Drawing"],
    workEnvironment: "Garage, Workshop",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [
      { collegeId: "tti-chumey", programId: "diploma-auto", programName: "Diploma in Auto Mechanics at TTI Chumey" },
    ],
    icon: "wrench",
    color: "#6b7280",
  },
  {
    id: "career-electrician",
    title: "Electrician",
    name: "Electrician",
    slug: "electrician",
    description: "Install, maintain, and repair electrical systems in residential, commercial, and industrial settings.",
    category: "Vocational",
    industry: "Construction",
    riasecCode: "RI",
    hollandCodes: ["R", "I"],
    educationLevel: "certificate",
    typicalSalary: "Nu. 12,000 - 35,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Electrical Knowledge", "Safety", "Problem Solving", "Blueprint Reading"],
    subjects: ["Physics", "Mathematics"],
    workEnvironment: "Construction Site, Building",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "tti-rangjung", programId: "cert-electrical", programName: "Certificate in Electrical at TTI Rangjung" },
      { collegeId: "tti-thimphu", programId: "diploma-electrical", programName: "Diploma in Electrical at TTI Thimphu" },
    ],
    icon: "lightbulb",
    color: "#fbbf24",
  },
  {
    id: "career-carpenter",
    title: "Carpenter",
    name: "Carpenter",
    slug: "carpenter",
    description: "Construct, repair, and install building frameworks and structures using wood and other materials.",
    category: "Vocational",
    industry: "Construction",
    riasecCode: "R",
    hollandCodes: ["R"],
    educationLevel: "certificate",
    typicalSalary: "Nu. 12,000 - 30,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Woodworking", "Measurement", "Blueprint Reading", "Safety"],
    subjects: ["Mathematics", "Technical Drawing"],
    workEnvironment: "Construction Site, Workshop",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "tti-rangjung", programId: "diploma-furniture", programName: "Diploma in Furniture Making at TTI Rangjung" },
    ],
    icon: "hammer",
    color: "#a16207",
  },
  {
    id: "career-hospitality-professional",
    title: "Hospitality Professional",
    name: "Hospitality Professional",
    slug: "hospitality-professional",
    description: "Work in hotels, restaurants, or tourism providing excellent guest services. Critical for Bhutan's tourism sector.",
    category: "Hospitality",
    industry: "Tourism",
    riasecCode: "ESA",
    hollandCodes: ["E", "S", "A"],
    educationLevel: "certificate",
    typicalSalary: "Nu. 12,000 - 35,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Customer Service", "Communication", "Language", "Cultural Awareness"],
    subjects: ["English", "Dzongkha", "Business Studies"],
    workEnvironment: "Hotel, Restaurant, Tourist Facility",
    bhutanSpecific: true,
    bhutanDemand: "very-high",
    rubPrograms: [
      { collegeId: "dsp-hotel", programId: "cert-hospitality", programName: "Certificate in Hospitality (Desuung)" },
    ],
    icon: "utensils",
    color: "#f97316",
  },

  // ============================================================================
  // LEGAL & GOVERNMENT (E, S, I)
  // ============================================================================
  {
    id: "career-lawyer",
    title: "Lawyer",
    name: "Lawyer",
    slug: "lawyer",
    description: "Represent clients in legal matters, provide legal advice, and prepare legal documents.",
    category: "Legal",
    industry: "Legal",
    riasecCode: "EAS",
    hollandCodes: ["E", "A", "S"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 30,000 - 80,000+/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Legal Knowledge", "Research", "Communication", "Critical Thinking"],
    subjects: ["English", "History", "Political Science"],
    workEnvironment: "Office, Court",
    bhutanSpecific: true,
    bhutanDemand: "medium",
    rubPrograms: [
      { collegeId: "jswwsl", programId: "llb", programName: "LL.B at JSW Law School" },
    ],
    icon: "gavel",
    color: "#7c3aed",
  },
  {
    id: "career-civil-servant",
    title: "Civil Servant",
    name: "Civil Servant",
    slug: "civil-servant",
    description: "Work in government agencies to implement policies, provide public services, and administer programs.",
    category: "Government",
    industry: "Government",
    riasecCode: "CES",
    hollandCodes: ["C", "E", "S"],
    educationLevel: "bachelor",
    typicalSalary: "Nu. 18,000 - 60,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "stable",
    skills: ["Administration", "Communication", "Policy Knowledge", "Public Service"],
    subjects: ["Varies by position"],
    workEnvironment: "Government Office",
    bhutanSpecific: true,
    bhutanDemand: "stable",
    rubPrograms: [],
    icon: "landmark",
    color: "#1e3a8a",
  },

  // ============================================================================
  // SCIENCE & RESEARCH (I, R, A)
  // ============================================================================
  {
    id: "career-scientist",
    title: "Scientist (Researcher)",
    name: "Scientist",
    slug: "scientist",
    description: "Conduct research in various scientific fields, analyze data, and contribute to scientific knowledge.",
    category: "Science",
    industry: "Research",
    riasecCode: "IAR",
    hollandCodes: ["I", "A", "R"],
    educationLevel: "master",
    typicalSalary: "Nu. 30,000 - 80,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "medium",
    skills: ["Research Methods", "Data Analysis", "Critical Thinking", "Scientific Writing"],
    subjects: ["Physics", "Chemistry", "Biology", "Mathematics"],
    workEnvironment: "Laboratory, Office, Field",
    bhutanSpecific: false,
    bhutanDemand: "medium",
    rubPrograms: [
      { collegeId: "sherubtse", programId: "bsc-physical", programName: "B.Sc. Physical Science at Sherubtse" },
      { collegeId: "sherubtse", programId: "bsc-life", programName: "B.Sc. Life Science at Sherubtse" },
    ],
    icon: "microscope",
    color: "#0891b2",
  },
  {
    id: "career-lab-technician",
    title: "Laboratory Technician",
    name: "Lab Technician",
    slug: "lab-technician",
    description: "Perform laboratory tests, analyze samples, and maintain lab equipment for medical or scientific purposes.",
    category: "Science",
    industry: "Healthcare",
    riasecCode: "IRC",
    hollandCodes: ["I", "R", "C"],
    educationLevel: "diploma",
    typicalSalary: "Nu. 15,000 - 40,000/month",
    salaryCurrency: "BTN",
    growthOutlook: "high",
    skills: ["Lab Techniques", "Attention to Detail", "Equipment Maintenance", "Data Recording"],
    subjects: ["Biology", "Chemistry", "Physics"],
    workEnvironment: "Laboratory",
    bhutanSpecific: true,
    bhutanDemand: "high",
    rubPrograms: [],
    icon: "flask",
    color: "#0e7490",
  },
];

// ============================================================================
// SEED FUNCTION
// ============================================================================

async function seedCareers() {
  console.log("🌱 Starting to seed careers database...");
  console.log(`   Total careers to insert: ${CAREERS_DATA.length}`);

  const now = new Date();
  let inserted = 0;
  let updated = 0;

  for (const career of CAREERS_DATA) {
    try {
      // Check if career exists
      const existing = await db.query.careers.findFirst({
        where: (careers, { eq }) => eq(careers.id, career.id),
      });

      if (existing) {
        // Update existing career
        await db
          .update(careers)
          .set({
            ...career,
            updatedAt: now,
          })
          .where(eq(careers.id, career.id));
        updated++;
        console.log(`   ✓ Updated: ${career.name}`);
      } else {
        // Insert new career
        await db.insert(careers).values({
          ...career,
          createdAt: now,
          updatedAt: now,
        });
        inserted++;
        console.log(`   + Inserted: ${career.name}`);
      }
    } catch (error) {
      console.error(`   ✗ Error with career ${career.name}:`, error);
    }
  }

  console.log("\n✅ Careers seeding completed!");
  console.log(`   Inserted: ${inserted}`);
  console.log(`   Updated:  ${updated}`);
  console.log(`   Total:    ${inserted + updated}/${CAREERS_DATA.length}`);
}

// ============================================================================
// RUN SEED
// ============================================================================

seedCareers()
  .then(() => {
    console.log("\n🎉 Careers database seeded successfully!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("\n❌ Error seeding careers:", error);
    process.exit(1);
  });

// Export for use in other scripts
export { CAREERS_DATA };
